In [ ]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.6-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\usuario\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.5 MB 8.6 MB/s eta 0:00:02
   ------------- -------------------------- 3.9/11.5 MB 10.0 MB/s eta 0:00:01
   --------------------- ------------------ 6.0/11.5 MB 10.2 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 10.4 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 10.3 MB/s eta 0:00:00
Downloading numpy-2.2.6-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.6 MB 11.1 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.6 MB 11.2 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 11.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 11.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.8 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.2.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Usuario\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [8]:
# Cargar el archivo
df = pd.read_csv("C:\\Users\\Usuario\\Documents\\datos imb\\title.basics.tsv", sep="\t", low_memory=False)
df.head

<bound method NDFrame.head of              tconst  titleType               primaryTitle  \
0         tt0000001      short                 Carmencita
1         tt0000002      short     Le clown et ses chiens
2         tt0000003      short               Poor Pierrot
3         tt0000004      short                Un bon bock
4         tt0000005      short           Blacksmith Scene
...             ...        ...                        ...
11681112  tt9916848  tvEpisode              Episode #3.17
11681113  tt9916850  tvEpisode              Episode #3.19
11681114  tt9916852  tvEpisode              Episode #3.20
11681115  tt9916856      short                   The Wind
11681116  tt9916880  tvEpisode  Horrid Henry Knows It All

                      originalTitle isAdult startYear endYear runtimeMinutes  \
0                        Carmencita       0      1894      \N              1
1            Le clown et ses chiens       0      1892      \N              5
2                    Pauvre Pierrot       0      1892      \N              5
3                       Un bon bock       0      1892      \N             12
4                  Blacksmith Scene       0      1893      \N              1
...                             ...     ...       ...     ...            ...
11681112              Episode #3.17       0      2009      \N             \N
11681113              Episode #3.19       0      2010      \N             \N
11681114              Episode #3.20       0      2010      \N             \N
11681115                   The Wind       0      2015      \N             27
11681116  Horrid Henry Knows It All       0      2014      \N             10

                              genres
0                  Documentary,Short
1                    Animation,Short
2           Animation,Comedy,Romance
3                    Animation,Short
4                              Short
...                              ...
11681112                       Drama
11681113                       Drama
11681114                       Drama
11681115                       Short
11681116  Adventure,Animation,Comedy

[11681117 rows x 9 columns]>

In [12]:
df.describe

<bound method NDFrame.describe of              tconst  titleType               primaryTitle  \
0         tt0000001      short                 Carmencita
1         tt0000002      short     Le clown et ses chiens
2         tt0000003      short               Poor Pierrot
3         tt0000004      short                Un bon bock
4         tt0000005      short           Blacksmith Scene
...             ...        ...                        ...
11681112  tt9916848  tvEpisode              Episode #3.17
11681113  tt9916850  tvEpisode              Episode #3.19
11681114  tt9916852  tvEpisode              Episode #3.20
11681115  tt9916856      short                   The Wind
11681116  tt9916880  tvEpisode  Horrid Henry Knows It All

                      originalTitle isAdult startYear endYear runtimeMinutes  \
0                        Carmencita       0      1894      \N              1
1            Le clown et ses chiens       0      1892      \N              5
2                    Pauvre Pierrot       0      1892      \N              5
3                       Un bon bock       0      1892      \N             12
4                  Blacksmith Scene       0      1893      \N              1
...                             ...     ...       ...     ...            ...
11681112              Episode #3.17       0      2009      \N             \N
11681113              Episode #3.19       0      2010      \N             \N
11681114              Episode #3.20       0      2010      \N             \N
11681115                   The Wind       0      2015      \N             27
11681116  Horrid Henry Knows It All       0      2014      \N             10

                              genres
0                  Documentary,Short
1                    Animation,Short
2           Animation,Comedy,Romance
3                    Animation,Short
4                              Short
...                              ...
11681112                       Drama
11681113                       Drama
11681114                       Drama
11681115                       Short
11681116  Adventure,Animation,Comedy

[11681117 rows x 9 columns]>

In [11]:
df.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres'],
      dtype='object')

In [13]:
print("Tipos de datos:\n", df.dtypes) #data types - tipos de datos

Tipos de datos:
 tconst            object
titleType         object
primaryTitle      object
originalTitle     object
isAdult           object
startYear         object
endYear           object
runtimeMinutes    object
genres            object
dtype: object

In [9]:
df[df['titleType'] == 'movie'].shape[0]

715824

In [10]:
df['genres'].value_counts()

genres
Drama                          1314605
Comedy                          759710
Talk-Show                       738664
News                            608837
Documentary                     563031
                                ...
Animation,Horror,Talk-Show           1
Animation,Biography,Western          1
Talk-Show,Thriller                   1
Biography,Crime,Fantasy              1
Action,Biography,News                1
Name: count, Length: 2388, dtype: int64

In [15]:
print("Ver Tipo , Titulo principal , duracion:")
df[['titleType', 'primaryTitle', 'runtimeMinutes']]

Ver Tipo , Titulo principal , duracion:

          titleType               primaryTitle runtimeMinutes
0             short                 Carmencita              1
1             short     Le clown et ses chiens              5
2             short               Poor Pierrot              5
3             short                Un bon bock             12
4             short           Blacksmith Scene              1
...             ...                        ...            ...
11681112  tvEpisode              Episode #3.17             \N
11681113  tvEpisode              Episode #3.19             \N
11681114  tvEpisode              Episode #3.20             \N
11681115      short                   The Wind             27
11681116  tvEpisode  Horrid Henry Knows It All             10

[11681117 rows x 3 columns]

In [16]:
print("Ordenado por cantidad de minutos")
df.sort_values(by= "runtimeMinutes", ascending=False)

Ordenado por cantidad de minutos

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
5840558,tt22984284,short,Game of Clones,Game of Clones,0,2021,\N,\N,Short
6924950,tt28752086,tvEpisode,Episode #1.38,Episode #1.38,0,1969,\N,\N,\N
6924897,tt28752005,tvEpisode,Episode #1.484,Episode #1.484,0,2023,\N,\N,"Drama,Romance"
6924898,tt28752006,tvEpisode,Episode dated 3 August 2010,Episode dated 3 August 2010,0,2010,\N,\N,Talk-Show
6924899,tt28752008,tvEpisode,Episode #1.486,Episode #1.486,0,2023,\N,\N,"Drama,Romance"
...,...,...,...,...,...,...,...,...,...
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
436283,tt0454640,short,The Talk,The Talk,0,2003,\N,0,"Comedy,Short"
333156,tt0348126,short,Storm P. tegner de Tree Små Mænd,Storm P. tegner de Tree Små Mænd,0,1920,\N,0,"Animation,Short"
896384,tt0926344,short,V-r,V-r,0,2006,\N,0,Short
803662,tt0830188,short,The Last Flight,The Last Flight,0,2005,\N,0,"Comedy,Short"